config/routes.rb
Rails.application.routes.draw do
	resources :items, only: :index do 
		post 'add', on: :member
		delete 'remove', on: :member
	end

	resources :baskets, only: :show 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
	has_and_belongs_to_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	validates :name, presence: true
	validates :price, presence: true
	has_and_belongs_to_many :baskets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_forgery_protection
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
	def show
		@basket = Basket.first
		render :show
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all
		render :index
	end

	def add
		basket = Basket.first
		item = Item.find_by(id: params[:id])
		qty = params[:qty].to_i
		qty.times { basket.items << item }
		redirect_to items_url
	end

	def remove
		basket = Basket.first
		item = Item.find_by(id: params[:id])
		basket.items.delete(item)
		redirect_to basket_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/baskets/show.html.erb
<h1>Basket Items</h1>

<table>
	<thead>
		<tr>
			<th>Item</th>
			<th>Price</th>
			<th>Quantity:</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @basket.items.uniq.each do |item| %> 
			<tr>
				<td><%= item.name %></td>
				<td><%= item.price %></td>

				<% item_id = item[:id] %>
				<% same_basket_items = @basket.items.where("id = '#{item_id}'") %>
				<td><%= item_qty = same_basket_items.count %></td>

				<td><%= button_to "Remove", remove_item_url(item), method: :delete %></td>
			</tr>
		<% end %>
	</tbody>
</table>


<%= link_to "Back to Item List", items_path %>

<%#= render 'shared/table', items: @basket.items, action: :show %>

app/views/items/_item.html.erb
<td><%= item.name %></td>
<td><%= item.price %></td>

app/views/items/index.html.erb
<h1>Item list</h1>

<table>
	<thead>
		<tr>
			<th>Item</th>
			<th>Price</th>
			<th>Quantity:</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @items.each do |item| %> 
			<tr>
				<td><%= item.name %></td>
				<td><%= item.price %></td>

					<form method="post" action="/items/<%= item[:id] %>/add" class="button_to">
						<td>
								<select id="quantity" name="qty">
									<option value="0" disabled selected>0</option>
									<% (1..10).each do |i| %>
										<option value="<%= i %>"><%= i %></option>
									<% end %>
								</select>
						</td>

						<td><input type="submit" value="Add to basket"/></td>
					</form>
				
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "View Basket", basket_path([1]) %>

<%#= render 'shared/table', items: @items, action: :index %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheckoutSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_table.html.erb
<!-- UNDER CONSTRUCTION -->

<table>
	<thead>
		<tr>
			<th>Item</th>
			<th>Price</th>
			<th>Quantity:</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% items.each do |item| %> 
			<tr>
				<td><%= item.name %></td>
				<td><%= item.price %></td>

				<% if action == :show %>
					<% item_id = item[:id] %>
					<% same_basket_items = Basket.first.items.where("id = '#{item_id}'") %>
					<td><%= item_qty = same_basket_items.count %></td>
						


					<td><%= button_to "Remove item", remove_item_url(item), method: :delete %></td>
				<% else %>
					<form method="post" action="/items/<%= item[:id] %>/add" class="button_to">
						<td>
								<select id="quantity" name="qty">
									<option value="0" disabled selected>0</option>
									<% (1..10).each do |i| %>
										<option value="<%= i %>"><%= i %></option>
									<% end %>
								</select>
						</td>

						<td><input type="submit" value="Add to basket"/></td>
					</form>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>